kind: ModelTraining
id: hl7fwa-model
spec:
  model:
    name: hl7fwa
    version: 1.1
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/sklearn/hl7fwa
  reference: origin/mvplatform-demo
  data:
    - connName: hl7fwaclaimsprepared
      localPath: mlflow/sklearn/hl7fwa/claims.snappy.parquet
    - connName: hl7fwakafkaparquetfile
      localPath: mlflow/sklearn/hl7fwa/test.snappy.parquet
  hyperParameters:
    num_estimators: "10"
  resources:
    limits:
      cpu: 2024m
      memory: 2024Mi
    requests:
      cpu: 1024m
      memory: 1024Mi
  vcsName: legion-examples